export const LOGIN = 'login'
export const ALL_CUSTOMER_APPLICATIONS = 'customer/get_all_applications'
export const UPDATE_PASSWORD = 'customer/update-password'
export const ALL_SERVICES = 'customer/get_all_services'
export const GET_FORM_DATA = 'customer/get_form_data'
